name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://Licht1183:$HF@huggingface.co/spaces/Licht1183/CTCD_Drug_Classification_Model
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push https://Licht1183:$HF@huggingface.co/spaces/Licht1183/CTCD_Drug_Classification_Model main
